CREATE DATABASE QuanLi_Pizza
USE QuanLi_Pizza

CREATE TABLE NhanVien (
	MaNV VARCHAR(10) NOT NULL,
	TenNV NVARCHAR(50) NOT NULL,
	ChucVu NVARCHAR(50),
	NgayVaoLam DATE,
	Luong DECIMAL(10,2),
	SDT VARCHAR(15) UNIQUE NOT NULL,
	DiaChi NVARCHAR(50),
	PRIMARY KEY (MaNV)
);

CREATE TABLE KhachHang (
	MaKH VARCHAR(10) NOT NULL,
	TenKH NVARCHAR(50) NOT NULL,
	SDT VARCHAR(15) UNIQUE NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	PRIMARY KEY (MaKH)
);

CREATE TABLE DonHang (
	MaDH VARCHAR(10) NOT NULL,
	MaKH VARCHAR(10) NOT NULL,
	MaNV VARCHAR(10) NOT NULL,
	NgayDat DATE,
	NgayGiao DATE,
	TongTien DECIMAL(10,2),
	TrangThai NVARCHAR(50) DEFAULT N'Chờ xử lý',
	PRIMARY KEY (MaDH),
	FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
	FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE INDEX idx_MaKH ON DonHang(MaKH);

CREATE TABLE ChiTietDonHang (
	MaCTDH VARCHAR(10) NOT NULL,
	MaDH VARCHAR(10) NOT NULL,
	MaSP VARCHAR(10) NOT NULL,
	SoLuong INT,
	Gia DECIMAL(10,2),
	PRIMARY KEY (MaCTDH),
	FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),
	FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH)
);

CREATE INDEX idx_MaDH ON ChiTietDonHang(MaDH);

CREATE TABLE SanPham (
	MaSP VARCHAR(10) NOT NULL,
	TenSP NVARCHAR(50) NOT NULL,
	Gia DECIMAL(10,2),
	Size VARCHAR(10),
	MoTa NVARCHAR(50),
	PRIMARY KEY (MaSP)
);

CREATE TABLE NguyenLieu (
	MaNL VARCHAR(10) NOT NULL,
	TenNL NVARCHAR(50) NOT NULL,
	DonViTinh NVARCHAR(20),
	SoLuong INT,
	PRIMARY KEY (MaNL)
);

CREATE TABLE Kho (
	MaKho VARCHAR(10) NOT NULL,
	MaNL VARCHAR(10) NOT NULL,
	SoLuongTon INT,
	PRIMARY KEY (MaKho),
	FOREIGN KEY (MaNL) REFERENCES NguyenLieu(MaNL)
);